include:
  - project: 'externalci/ci-image'
    ref: master
    file: '.gitlab-ci-default.yaml'

stages:
  - build
  - test
  - release
  - trigger

###############################################################
# Build Stage
###############################################################

dev-pypi:
  extends: .dev-pypi

###############################################################
# Test Stage
###############################################################

test-run310:
  tags:
    - stage-kube-newer
  image: python:3.10
  stage: test
  before_script:
    - pip install --upgrade pip
  script:
    - pip install .[tests]
    - pytest

test-run311:
  tags:
    - stage-kube-newer
  image: python:3.11
  stage: test
  before_script:
    - pip install --upgrade pip
  script:
    - pip install .[tests]
    - pytest

test-run312:
  tags:
    - stage-kube-newer
  image: python:3.12
  stage: test
  before_script:
    - pip install --upgrade pip
  script:
    - pip install .[tests]
    - pytest

###############################################################
# Release Stage
###############################################################

release-pypi:
  extends: .release-pypi-public
